### ISSUE TITLE
Exact meaning of T, and of None returned by sampler

### ISSUE THREAD

**Issue by fasiha** [Networks-Learning/memorize#2]
This might be a very silly question but I just want to make sure I understand. Is `T` here https://github.com/Networks-Learning/memorize/blob/6ee10ddc165d8da1d76e2a750f4dc038d7bcd254/memorize.py#L11
simply a maximum on the values that `sampler` can return? I.e., `sampler` will return `None` instead of suggesting scheduling an item at time `t>T`, which indicates that there's no need to schedule that particular item in the coming `T` time units?

Thank you!

**Comment by musically-ut** [comment]
Yes, that is the correct interpretation.
