### ISSUE TITLE
Typo in website?

### ISSUE THREAD

**Issue by fasiha** [Networks-Learning/memorize#3]
In the website, you say "if the user has completely forgotten the item … the learner will see review events with rate $q^{-1/2}$ per unit of time" but in playing with memorize.py, I think you mean $q^{+1/2}$?

For example. When `q=1e-2`, the mean output of `sampler` for very large `n_t=1e2` (i.e., recall probability very close to zero) is 0.1. And similarly when `q=1e-3`, the average is 0.03 (`sqrt(q)` in both cases).

**Comment by musically-ut** [comment]
If the rate of a Poisson process is `1 / sqrt(q)` items per unit time, then the first sample you would see from it would be `sqrt(q)` units of time in expectation, and that is what your numbers indicate as well.

Does that help clear up the confusion?

**Comment by fasiha** [comment]
Yes I see, it's the confusion between 'rate' and 'scale', got it! Thank you!
