### ISSUE TITLE
Why the result of sampler(n_t, q, T) is not an expectation value?

### ISSUE THREAD

**Issue by L-M-Sherlock** [Networks-Learning/memorize#6]

**Comment by L-M-Sherlock** [comment]
Could I use the arithmetic mean of the sampler's outputs? (if I call the sampler 100 times)

**Comment by musically-ut** [comment]
The result of the sampler has to be a random duration drawn from the given density function for the underlying theory to guarantee optimal learning.

If you would like, you can take the average of N samples for your particular application.

Unfortunately, there is likely no closed form formula that can compute that average [[1]], so it is very likely that you'll have to take empirical samples (with a fixed seed). 

[1]: https://www.wolframalpha.com/input/?i=int+e%5E%7B-+ax+-+e%5E%7B-bx%7D%7D
[[1]]: The integration of the survival function results in an integral of the following form: https://www.wolframalpha.com/input/?i=int+e%5E%7B-+ax+-+e%5E%7B-bx%7D%7D

**Comment by L-M-Sherlock** [comment]
Thanks for your answer, I get it.
